### ISSUE TITLE
UnboundLocalError: local variable 'R_tbl' referenced before assignment

### ISSUE THREAD

**Issue by ciaoyee** [eeb177-W17/eeb177-W17.github.io#40]
After going through iterations for PyRate, and I try the -plot command to get the plots, the error "UnboundLocalError: local variable 'R_tbl' referenced before assignment" comes up and nothing in the PyRate github makes sense in ways that I could fix it? So I have a ton of iterations and no way to plot, please helpp.

combining all files....skipping file: /Users/yeechau/Downloads/eeb-174-final-project/pyrate_mcmc_logs/lizard_pbdb_1_marginal_rates.log
Traceback (most recent call last):
  File "/Users/yeechau/PyRate/PyRate.py", line 2650, in <module>
    plot_RTT(path_dir_log_files, burnin, name_file,one_file,root_plot,plot_type)
  File "/Users/yeechau/PyRate/PyRate.py", line 318, in plot_RTT
    print(shape(R_tbl))
UnboundLocalError: local variable 'R_tbl' referenced before assignment

**Comment by gauravsk** [comment]
@ciaoyee Can you add your PyRate log files to your github repo?

**Comment by ciaoyee** [comment]
@gauravsk Just added em!

**Comment by gauravsk** [comment]
@ciaoyee What's the difference between `lizard_pbdb_1_G_marginal_rates.log` and `lizard_pbdb_1_marginal_rates.log`? I could get a plot of the first but not of the second- are you having the same issue?

**Comment by gauravsk** [comment]
Actually, it looks like the `lizard_pbdb_1_marginal_rates.log` file is super tiny, only 20kb (vs. 1.5mb for the other.) My guess is that the PyRate run that made the small log file just terminated early on. 

Here's the PDF i get from `lizard_pbdb_1_G_marginal_rates.log`: [lizard_pbdb_1_G_marginal_rates_RTT.pdf](https://github.com/eeb177-W17/eeb177-W17.github.io/files/859537/lizard_pbdb_1_G_marginal_rates_RTT.pdf)
